<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   design
 * @package    TIG_Postcode
 * @copyright  Copyright (c) 2012 Total Internet Group (http://www.totalinternetgroup.nl)
 * @author     Total Internet Group (http://www.totalinternetgroup.nl)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<form action="" id="co-shipping-form">
    <ul class="form-list">
    <?php if ($this->customerHasAddresses()): ?>
       <li class="wide">
           <label for="shipping-address-select"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label>
           <div class="input-box">
               <?php echo $this->getAddressesHtmlSelect('shipping') ?>
           </div>
       </li>
    <?php endif ?>
        <li id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
            <fieldset>
                <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
                <ul>
                    <li class="fields"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?></li>
                    <li class="fields">
                        <div class="fields">
                            <label for="shipping:company"><?php echo $this->__('Company') ?></label>
                            <div class="input-box">
                                <input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text" onchange="shipping.setSameAsBilling(false);" />
                            </div>
                        </div>
            <?php if(false): ?>
                        <div class="fields">
                            <label for="shipping:email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                            <div class="input-box">
                                <input type="text" name="shipping[email]" id="shipping:email" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                            </div>
                        </div>
            <?php endif ?>
                    </li>
                    <li class="fields">
                        <div class="field">
                            <label for="shipping:telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                            <div class="input-box">
                                <input type="text" name="shipping[telephone]" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry" id="shipping:telephone" onchange="shipping.setSameAsBilling(false);" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="shipping:fax"><?php echo $this->__('Fax') ?></label>
                            <div class="input-box">
                                <input type="text" name="shipping[fax]" value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text" id="shipping:fax" onchange="shipping.setSameAsBilling(false);" />
                            </div>
                        </div>
                    </li>
                    <li class="fields">
                        <div class="field">
                            <label for="shipping:country_id" class="required"><em>*</em><?php echo Mage::helper('tig_postcode')->__('Country') ?></label>
                            <div class="input-box">
                                <?php echo $this->getCountryHtmlSelect('shipping') ?>
                            </div>
                        </div>
                        <div class="field" id="postcode-shipping-region">
                            <label for="shipping:region" class="required"><em>*</em><?php echo Mage::helper('tig_postcode')->__('State/Province') ?></label>
                            <div class="input-box">
                                <select id="shipping:region_id" name="shipping[region_id]" title="<?php echo Mage::helper('tig_postcode')->__('State/Province') ?>" class="validate-select" style="display:none;">
                                    <option value=""><?php echo Mage::helper('tig_postcode')->__('Please select region, state or province') ?></option>
                                </select>
                                <script type="text/javascript">
                                //<![CDATA[
                                    $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                //]]>
                                </script>
                                <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>" title="<?php echo Mage::helper('tig_postcode')->__('State/Province') ?>" class="input-text" style="display:none;" />
                            </div>
                        </div>
                    </li>
                    <li class="fields">
                        <div class="field">
                            <label for="shipping:postcode" class="required"><em>*</em><?php echo Mage::helper('tig_postcode')->__('Zip/Postal Code') ?></label>
                            <img id="postcode-shipping-please-wait" style="display:none;" src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('tig_postcode')->__('Loading...') ?>" title="<?php echo Mage::helper('tig_postcode')->__('Loading...') ?>" />
                            <div class="input-box">
                                <input type="text" title="<?php echo Mage::helper('tig_postcode')->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international required-entry" onchange="shipping.setSameAsBilling(false);" />
                                <div style="display: none;" id="advice-validate:shipping:postcode" class="validation-advice"><?php echo Mage::helper('tig_postcode')->__('Check that the Zip/Postal Code and the House Number correctly entered!') ?></div>
                            </div>
                        </div>
                        <div class="field  field-small">
                            <label for="shipping:street2" class="required"><em>*</em><?php echo Mage::helper('tig_postcode')->__('House Number') ?></label>
                            <div class="input-box">
                                <input type="text" title="<?php echo Mage::helper('tig_postcode')->__('House Number') ?>" id="shipping:virtual:street2" value="" class="input-text required-entry" onchange="shipping.setSameAsBilling(false);" />
                            </div>
                        </div>
                        <div class="field  field-small">
                            <label for="shipping:street3"><?php echo Mage::helper('tig_postcode')->__('Extension') ?></label>
                            <div class="input-box">
                                <input type="text" title="<?php echo Mage::helper('tig_postcode')->__('Extension') ?>" id="shipping:virtual:street3" value="" class="input-text" onchange="shipping.setSameAsBilling(false);" />
                            </div>
                        </div>
                    </li>
                    <?php if (Mage::getStoreConfig('tig_postcode/exclude_fields/field_extra_is_enabled')): ?>
                    <li class="wide">
                        <label class="required" for="shipping:street4"><?php echo Mage::helper('tig_postcode')->__('Extra') ?></label>
                        <div class="input-box">
                            <input type="text" class="input-text" value="" id="shipping:virtual:street4" title="<?php echo Mage::helper('tig_postcode')->__('Extra') ?>" onchange="shipping.setSameAsBilling(false);" />
                        </div>
                    </li>
                    <?php endif; ?>
                    <li class="fields">
                        <div class="field">
                            <label for="shipping:street1" class="required"><em>*</em><?php echo Mage::helper('tig_postcode')->__('Street Address') ?></label>
                            <div class="input-box">
                                <input type="text" title="<?php echo Mage::helper('tig_postcode')->__('Street Address') ?>" id="shipping:virtual:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="input-text required-entry" onchange="shipping.setSameAsBilling(false);" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="shipping:city" class="required"><em>*</em><?php echo Mage::helper('tig_postcode')->__('City') ?></label>
                            <div class="input-box">
                                <input type="text" title="<?php echo Mage::helper('tig_postcode')->__('City') ?>" name="shipping[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" class="input-text required-entry" id="shipping:city" onchange="shipping.setSameAsBilling(false);" />
                            </div>
                        </div>
                    </li>

                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                    <li class="control">
                        <input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="shipping:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label></li>
                <?php else:?>
                    <li class="no-display"><input type="hidden" name="shipping[save_in_address_book]" value="1" /></li>
                <?php endif;?>
                </ul>
            </fieldset>
        </li>
        <li class="control">
            <input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Use Billing Address') ?>" onclick="shipping.setSameAsBilling(this.checked)" class="checkbox" /><label for="shipping:same_as_billing"><?php echo $this->__('Use Billing Address') ?></label>
        </li>
    </ul>
    <div class="buttons-set" id="shipping-buttons-container">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="button" class="button" title="<?php echo $this->__('Continue') ?>" onclick="shipping.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span id="shipping-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
    <?php for ($i=1;$i<5;$i++): ?>
    <input type="hidden" name="shipping[street][]" id="shipping:street<?php echo $i ?>" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet($i)) ?>" />
    <?php endfor;?>
</form>

<script type="text/javascript">
//<![CDATA[
    for (var i=1;i<5;i++) {
        var _virtualField = 'shipping:virtual:street'+i;
        var _field = 'shipping:street'+i;
        if ($(_virtualField)) $(_virtualField).value = $(_field).value;
    }
    Shipping.prototype._save_base = Shipping.prototype.save;
    Shipping.prototype.save = function() {
        for (var i=1;i<5;i++) {
            var _virtualField = 'shipping:virtual:street'+i;
            var _field = 'shipping:street'+i;
            if ($(_virtualField)) $(_field).value = $(_virtualField).value;
        }
        if ($('postcode-shipping-please-wait').visible()) {
            return false;
        }
        this._save_base();
    }
    Shipping.prototype._syncWithBilling_base = Shipping.prototype.syncWithBilling;
    Shipping.prototype.syncWithBilling = function() {
        this._syncWithBilling_base();
        tigPostcodeUpdaterShipping.getData();
    }
    var shipping = new Shipping('co-shipping-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>',
        '<?php echo $this->getUrl('checkout/onepage/shippingMethod') ?>');
    var shippingForm = new VarienForm('co-shipping-form');
    shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
    //shippingForm.setElementsRelation('shipping:country_id', 'shipping:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
    $('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);

    //HTIG: fix for Magento CE 1.7
    if (typeof(countryRegions) === 'undefined') {
        var countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?>;
    }
    
    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', countryRegions, undefined, 'shipping:postcode');
    var tigPostcodeUpdaterShipping = new TigPostcodeUpdater('<?php echo $this->getUrl('tig_postcode/onepage', array('_secure' => true)); ?>', 'shipping:postcode', 'shipping:virtual:street2', 'shipping:virtual:street1', 'shipping:city', 'shipping:country_id', 'postcode-shipping-region', 'postcode-shipping-please-wait');
    tigPostcodeUpdaterShipping.getData();
//]]>
</script>